### PR TITLE
Only use ~ in class ref to hide prefix

### PR DESCRIPTION
**Pull request by dukebody**
The current contents are a bit misleading and makes one think it's a typo.

### CODE REVIEW

**Comment by datapythonista** [comment]
Afaik the `~` is being used to link to classes in pandas. Not sure why, will check.

**Comment by TomAugspurger** [comment]
`~` hides the class name. We'll occasionally use it when referring to a method on either Series or DataFrame, instead of doing

    :meth:`Series.head` or :meth:`DataFrame.head`

**Comment by dukebody** [comment]
Found it! http://www.sphinx-doc.org/en/stable/domains.html#cross-referencing-syntax

I will modify the PR to say this.

**Comment by datapythonista** [comment]
Thanks a lot, very useful.

**Comment by jorisvandenbossche** [comment]
BTW, @dukebody also welcome to do this change in the version in the pandas docs as well

Now that is merged, we should maybe use that one to keep up to date and link to? To not duplicate the changes each time?

**Comment by dukebody** [comment]
@jorisvandenbossche done: https://github.com/pandas-dev/pandas/pull/20402

**Comment by dukebody** [comment]
> Now that is merged, we should maybe use that one to keep up to date and link to? To not duplicate the changes each time?

I agree. Should we delete the guide contents from this repo and replace every page with a link to the development version of the docs, like http://pandas-docs.github.io/pandas-docs-travis/contributing.html.

**Pull request merged**
