### PR TITLE
Added Ankara Chapter Details

### PR DESCRIPTION
**Pull request by Neuroscitechie**
Added location, time and location sponsor details.

### CODE REVIEW

**Comment by datapythonista** [comment]
Can you also update the event url please? So, instead of going to the home of your meetup, goes to the pandas sprint event.

Thanks!

**Comment by Neuroscitechie** [comment]
Just updated, thank you

**Comment by Neuroscitechie** [comment]
Also added logo

**Comment by datapythonista** [comment]
Merging pull request, but can you please update the coordinates (latitude and longitude) too? It may be misleading to have the point in the map in one place, and the actual address somewhere else.

Also, you should create a branch to make changes for a pull request, as explained in the documentation. Doing them in master is dangerous, and you can end up and situations when you need to undo all your changes, and do them again, which is complex.

**Comment by Neuroscitechie** [comment]
Just found the fork and edited the details that you requested, thanks for the tip.

**Pull request merged**
