### PR TITLE
Main website

### PR DESCRIPTION
**Pull request by sukanyamandal**
Updated the time and location details for PyData Mumbai.

### CODE REVIEW

**Comment by datapythonista** [comment]
Amazing, do you main updating the coordinates (latitude and longitude) too? Otherwise the marker will be in the wrong place. Thanks!

**Comment by sukanyamandal** [comment]
No I did not make any change in the latitude and longitude. I checked from google and there seem to be only 0.01 difference. Hence did not make an effort to change.

**Comment by datapythonista** [comment]
Ok, cool, thank you!

**Comment by sukanyamandal** [comment]
Thanks to you too! :)

**Comment by datapythonista** [comment]
I think the geo is 7 kms far away from the event address, up to you, but I think it may be confusing for people attending the event. I'd fix it.

Also, it'd be a good practice for using branches, you shouldn't open pull requests from master. In a best case scenario everything will work fine, like in this case, but in many circumstances you'll end up in situations where it's difficult to continue working in some changes, and you need to start again.

I'm preparing a screencast explaining all the concepts regarding pull requests, as they are tricky.

**Pull request merged**
