### PR TITLE
Fix multiple typos

### PR DESCRIPTION
**Pull request by akielbowicz**
Fixed typos in: - pandas/guide/pandas_setup.html
                        - pandas/guide/contents.html
                        - pandas/guide/organizers.html
                        - pandas/guide/pandas_docstring.html

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks a lot for taking the time to fix the typos. There are couple of things wrong with the pull request. The html files you fixes are generated automatically with sphinx from the `.rst` files in the `source/` directory. So, even if I merge the PR, your changes will be overwritten when we make another change.

Then, the commit adding the Buenos Aires sprint we already merged it's in this PR again. I think you probably created this branch from the previous instead of master. And if I'm not wrong we'll duplicate the event with the merge (it's strange that we don't get a conflict).

Do you mind fixing the typos to the `.rst` files in a new PR, and build the html files with `sphinx-build pandas/guide/source/ pandas/guide`? Thanks a lot!

**Comment by datapythonista** [comment]
Not sure if any of the typos fixed in #39 where the ones you fixed here. Make sure you pull the latest code before making the changes in the `.rst` files, to avoid conflicts. Thanks!

**Comment by akielbowicz** [comment]
Hi Marc, I made the changes in the `.rst` files but in the process of making the buid with sphinx I had a few problems.

First I had sphinx 1.6.6 and when it builds the pages they had many differences in format, in things like this:
```diff
-    background-color: #fff;
+    background-color: #ffffff;

...

-div.admonition tt.xref, div.admonition code.xref, div.admonition a tt {
-    background-color: #FBFBFB;
+div.admonition tt.xref, div.admonition a tt {
     border-bottom: 1px solid #fafafa;
 }
```
When I realized that this was a version problem, I tried to build with the same version that its built now, sphinx 1.7.0,  and it worked well. 
But now when I build the pages,  the changes made in #39 get reverted because they were made directly to the `.rst.txt` files. 

It took me a while to find out that the differences came from a version problem. So it would be good to include in the guides the version of sphinx to use in the project, given that the default version to install with `apt`, `conda` and `pip` all differ. Unless it doesn´t make much difference, as I see that the pages of *organizers* are built with sphinx 1.7.0 and the *contents* pages with sphinx 1.6.6 .

And , should I add the changes of #39 to `pandas_pr.rst and pandas_setup.rst` ? Or is better to make a new PR for this changes?

Cheers

**Comment by datapythonista** [comment]
Yep, we don't care that much on the sphinx version, and we keep changing these formatting depending on who sends the last pull request. Feel free to add any information you think can save people's time in the `organizers.rst` or any other document.

I don't quite get what you mean the changes where made in the `.rst.txt` files, I think those are temporary files generated by sphinx. I think it's what you say, but just to be clear, the process would be:
* Make the changes to the `source/*.rst` files
* Build html files with `sphinx-build`, no matter which version
* Send a PR with all changed files, the rst, the updated html, and the css or whatever that was changed by using another version of sphinx.

I think it'll be easier for you to send a new PR, but doesn't make a difference to me to approve this one if you update it, or reject this and approve another. Up to you.

Thanks!

**Pull request closed without merging**
