### PR TITLE
Added link for San Diego MeetUp

### PR DESCRIPTION
**Pull request by WillAyd**

### CODE REVIEW

**Comment by datapythonista** [comment]
Excellent! Feel free to add the logos of zeeto and cloudfare in the sponsors section too.

Btw, in most meetups we don't let people register directly, and instead we make them join the waiting list. This way we can ensure a good proportion of experienced people. You can join the London event if you want to see how it works. Feel free to manage it as you wish, but from my experience running the London sprints, if you've got only people new to pandas and to git, you'll end up very stressed, and the sprint won't be very productive.

**Comment by WillAyd** [comment]
You just do that through the RSVP option in MeetUp right? I’ve tried setting that a few times but it keeps unsetting itself. Before I was ending the RSVP an hour before the event, but I’ll try an entire day now and see if that sticks.

Otherwise if I’m way off on how to manage that in MeetUp let me know.

**Comment by datapythonista** [comment]
I've just set the maximum number of spots to 0, and then added a question "Please describe your experience in pandas and in contributing to open source. If you consider you can be part of an underrepresented community, please let us know too."

After that, everybody should get into the waiting list, and I keep reviewing the answers, and changing their status to "Going" to the ones I want.

Let me know if that doesn't work for you.

**Comment by WillAyd** [comment]
OK just set it up that way. If you have a minute any chance you can test it out on your end?

**Comment by datapythonista** [comment]
It doesn't seem to be working. May be you can try with the old interface: https://www.meetup.com/pythonsd/events/247689031/?action=edit

New meetup version is really buggy (besides the bad UX)

**Comment by WillAyd** [comment]
OK just used that - try again?

**Comment by datapythonista** [comment]
For what I saw, meetup has a new interface to edit the events:
https://www.meetup.com/pythonsd/events/247689031/edit/

and an old one:
https://www.meetup.com/pythonsd/events/247689031/?action=edit

And both of them have options to limit the number of attendees. If you already set it to zero, it should force everyone to get into the waiting list. As it doesn't work, I'd try with the other interface, and see if that works. May be you changed it, but it was a "Save changes" button somehwere (new meetup interface is really confusing, and that could be the problem). Otherwise, I don't know what else to do. Not sure how I did it, but it worked for me. If it just works at creation time, may be you can recreate the event.

**Comment by WillAyd** [comment]
Hmm yea I just tried with the old interface. I tried setting to zero but got the below error, so then I set it to 2 since there’s already two of us in there. I have it at 1 now.

I’m wondering if it’s not working for you because you RSVP’ed before the change was made? I’ll have my roommate test to see how it works for someone that hasn’t tried to join at all...

**Comment by datapythonista** [comment]
It's working now. :)

**Pull request merged**
