### PR TITLE
added Nairobi_chapter time and location

### PR DESCRIPTION
**Pull request by 4bic**

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks for the PR. Can you please update the link to the event (not the home of the meetup group) and the geolocation of the sprint? Thank you!

**Comment by 4bic** [comment]
@datapythonista  its done.

**Comment by datapythonista** [comment]
Thanks, can you update the latitude and the longitude please? So the marker in the map is in the exact location, and not somewhere random in Nairobi.

Thanks!

**Comment by datapythonista** [comment]
Excellent, thank you!

Assigned you a docstring in https://docs.google.com/spreadsheets/d/138095mUxOTOCCXmvQGz7YOh-0yWLoTH_8_IlrAI5w2c/edit#gid=0

Let us know if you need any help.

**Pull request merged**
