### PR TITLE
Added PyData Delhi to Pandas Sprint Page

### PR DESCRIPTION
**Pull request by MSanKeys963**

### CODE REVIEW

**Comment by datapythonista** [comment]
Great, do you mind updating the corrdinates (latitude and longitude)? It may be confusing for people in Delhi that the marker is not in the event address. Thanks!

**Comment by datapythonista** [comment]
Also, the way the website is implemented, you should add the sponsor logo if you want to have a link to it. Just the link doesn't do anything.

**Comment by datapythonista** [comment]
Great, thank you very much. Added a docstring for you to practice in https://docs.google.com/spreadsheets/d/138095mUxOTOCCXmvQGz7YOh-0yWLoTH_8_IlrAI5w2c/edit#gid=0

**Comment by MSanKeys963** [comment]
Thanks, @datapythonista . :)

**Pull request merged**
